DATA:
    QUICK_DATA:
      window_size : [30]
      stride_size : [1]
      features : ["close"]
      id_features: ["date"]
      scaler : [standard]
      validation_ratio: [ 0.15 ]
      test_ratio: 0.05
      THRESHOLD: 0.6
    MID_DATA:
      window_size: [32]
      stride_size: [1]
      features : ["close"]
      id_features: ["date"]
      scaler : [standard]
      validation_ratio: [ 0.15 ]
      test_ratio: 0.05
      THRESHOLD: 0.6



QUICK:
  ANOMALY:
    LSTM:
      module_name : "lstm"
      network_name : "LSTM_AnomalyNetwork"
      batch_size : [512]
      epochs : 5
      max_trials : 2


MID:
  ANOMALY:
    LSTM:
      module_name : "lstm"
      network_name : "LSTM_AnomalyNetwork"
      batch_size : [512]
      epochs : 200
      max_trials : 10







